#FIXME change file name to actual app name
#FIXME change to actual app name
name: $hyoo_template_app

#FIXME optional: change permissions if you don't want to allow everything
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-permissions
permissions: write-all

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hyoo/template' #FIXME namespace of this package
        modules: 'app' #FIXME which modules to build, remove line if only on module at the root
    
    #FIXME remove one of the following
    
    - uses: JS-DevTools/npm-publish@v1
      if: github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./mol/template/app/-/package.json #FIXME path to build module
        
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'hyoo/template/app/-' #FIXME path to build app
